// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var checkers;



  exports.checkers = checkers = {
    username: {
      hint: "between 4 and 12 letters long",
      f: function(x) {
        return x.length >= 4 && x.length <= 12;
      }
    },
    passphrase: {
      hint: "must be at least 12 letters long",
      f: function(x) {
        return x.length >= 12;
      }
    },
    email: {
      hint: "must be a valid email address",
      f: function(x) {
        return (x.length > 3) && x.match(/^\S+@\S+\.\S+$/);
      }
    },
    invite_code: {
      hint: "invite codes are 24 digits long",
      f: function(x) {
        return x.length === 24;
      }
    }
  };

}).call(this);
