// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var constants;



  exports.constants = constants = {
    version: 1,
    api_version: "1.0",
    canonical_host: "keybase.io",
    server: {
      host: "keybase.io",
      port: 443,
      no_tls: false
    },
    filenames: {
      config_dir: ".keybase",
      config_file: "config.json",
      session_file: "session.json",
      db_file: "keybase.sqlite3"
    },
    security: {
      pwh: {
        derived_key_bytes: 32
      },
      openpgp: {
        derived_key_bytes: 12
      },
      triplesec: {
        version: 3
      }
    },
    permissions: {
      dir: 0x1c0,
      file: 0x180
    },
    lookups: {
      username: 1,
      local_track: 2
    },
    ids: {
      sig_chain_link: "e0",
      local_track: "e1"
    },
    import_state: {
      NONE: 0,
      TEMPORARY: 1,
      FINAL: 2,
      CANCELED: 3
    },
    signature_types: {
      NONE: 0,
      SELF_SIG: 1,
      REMOTE_PROOF: 2,
      TRACK: 3,
      UNTRACK: 4,
      REVOKE: 5
    },
    time: {
      remote_proof_recheck_interval: 60 * 60 * 24
    }
  };

  constants.server.api_uri_prefix = "/_/api/" + constants.api_version;

}).call(this);
