// Generated by IcedCoffeeScript 1.6.3-g
(function() {


  exports.constants = {
    version: 1,
    api_version: "1.0",
    server: {
      host: "keybase.io",
      api_uri_prefix: "/_/api/1.0",
      port: 443,
      no_tls: false
    },
    filenames: {
      config_dir: ".keybase",
      config_file: "config.json"
    }
  };

}).call(this);
