// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var home;



  exports.home = home = function() {
    return process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
  };

}).call(this);
